### ISSUE TITLE
ERROR for clustal omega call clustalo

### ISSUE THREAD

**Issue by StephenLi55** [lotts/GLASSgo_ACC-Version#4]
Hi,

  I am trying to run GLASSgo on my sRNA sequence with the following input: 

   python3 GLASSgo.py -i fasta_files/Li_ANNOgesic_121.fa -d blastdb/RNACentral.fasta -t 16 -o test

  However, the following error was returned:

  ERROR for clustal omega call clustalo -i ./IDo1591689197.4863622.tmp --distmat-out ./IDX1591689197.491062.tmp --full --percent-id --output-order=input-order --max-hmm-iterations -1 --threads 16

  Is that some issue with my input fasta file? Or is my laptop lacking certain packages?

  FYI I have attached the input fasta file here.

  Best wishes,

  Stephen
  
[Li_ANNOgesic_121.fa.zip](https://github.com/lotts/GLASSgo/files/4752363/Li_ANNOgesic_121.fa.zip)

**Comment by lotts** [comment]
Dear Stephen, 
due to the high number of dependencies, we highly recommend making use of our GLASSgo docker container. GLASSgo is also available in the GALAXY's ToolShed and is part of the https://usegalaxy.eu server (free of charge). Maybe you read our latest publication about GLASSgo https://academic.oup.com/bioinformatics/advance-article/doi/10.1093/bioinformatics/btaa556/5850859?searchresult=1 . The document refers to various instruction videos, one for using the docker container and one for GALAXY.

Please let me know if my answer was helpful to you!

**Comment by StephenLi55** [comment]
Hi

  Thanks for getting back.

  I have tried to run it on either the web server version or the galaxy version. I realise both versions only compare my input sequence with NCBI database, but I am trying to compare my input with a collection of non-coding RNA sequences . Is there anyway to change the database into my customised database ?

  Regarding to the input parameter, would you mind explaining how the default E value and pairwise identity threshold was decided? I am concerned that my sRNA sequences are taken from Campylobacter, and previous work suggested that  Campylobacter sRNA sequence are not very conserved comparing to other bacterial species. Would it make sense to relax the E value and the pairwise identity threshold ?

  best wishes,

  Stephen
________________________________

**Comment by lotts** [comment]
Dear Stephen, 
of course, you can build your database from scratch. Therefore, you need the sequences in FASTA-format as well as a taxonomic lookup file.
If the BLAST+ software package is installed, you can use the following command to build your customized DB:

makeblastdb -in my_sequences.fasta -parse_seqids -taxid_map my_map.txt -title "my_customiced_DB" -dbtype nucl

my_sequences.fasta contains your sequences in FASTA-format
      => >CP000095.2 Prochlorococcus marinus str. NATL2A, complete genome
TAATAGATGGATACTATGTTTTTTGGATTACCCACAGAAACCACAGGTACTACTACTACTAATTCAATTT ...
my_map.txt connects the sequence ID with its taxonomic ID (one entry per line; space delimited)
      => CP000095.2 59920 

Regarding your question about E-Value and min. pairwise identity threshold, we got those by analyzing 40 different RFAM Families. The result of those 40 RFAM Families are shown in our publication (Figure 3).

Best,
steffen
